apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-reader
  namespace: default
rules:
- apiGroups: [""] #this indicate the core api group
  resources: ["pod"]
  verbs: ["get","watch","list"]